-- Issue 3-2 (Lab 3) — Requester -> User, real credentials/role.
--
-- Hand-written rather than generated by `prisma migrate dev`'s interactive rename-detection: this
-- dev database already holds real seeded/test data (154 Requester rows, 578 Ticket rows as of
-- writing) and the CLI's rename-vs-drop-and-recreate prompt needs a TTY this environment doesn't
-- have. `ALTER TABLE ... RENAME TO` is the one statement Postgres needs to keep every existing row
-- and every FK pointing at this table intact (specification.md §7 "Migration strategy", BR-37) —
-- Postgres tracks foreign keys by OID, not by name, so `Ticket.requesterId`'s constraint keeps
-- working across the rename with no change of its own. `Requester_pkey` and similar
-- auto-generated constraint/index names are left as-is (cosmetic only, Postgres does not rename
-- them automatically and there is no functional reason to).

-- 1. Rename the table itself. Every existing row (id, name, email, isActive, createdAt) survives
--    unchanged; every Ticket.requesterId FK keeps pointing at the same rows.
ALTER TABLE "Requester" RENAME TO "User";

-- 2. New enum for role.
CREATE TYPE "Role" AS ENUM ('REQUESTER', 'IT_STAFF', 'ADMINISTRATOR');

-- 3. New columns. Each NOT NULL column needs a one-time backfill value for the rows that already
--    exist; the temporary DEFAULT is dropped immediately after so schema.prisma (no @default on
--    passwordHash/role) and the live DB agree — every *future* insert must supply both explicitly.
--    - passwordHash backfills to '' (not a valid bcrypt hash) purely as a placeholder: the seed
--      script's upsert (by email) overwrites every migrated row with a real hash in the same
--      `npm run prisma:migrate && npm run prisma:seed` sequence this project already documents
--      running together (BR-38).
--    - role backfills to REQUESTER, which is factually correct for every existing migrated row —
--      Lab 2 never had any other kind of identity.
--    - mustChangePassword keeps its default (true) permanently, matching schema.prisma's
--      @default(true) — every migrated Requester lands in the first-login-change state (BR-38),
--      same as a freshly Administrator-created user would.
--    - updatedAt backfills to now(); its DEFAULT is then dropped since @updatedAt is managed by
--      Prisma Client on every future write, not by the database.
ALTER TABLE "User" ADD COLUMN "passwordHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ALTER COLUMN "passwordHash" DROP DEFAULT;

ALTER TABLE "User" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'REQUESTER';
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "User" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ALTER COLUMN "updatedAt" DROP DEFAULT;
